2018-10-05 20:38:38,712 ERROR: Exception on /favicon.ico [GET] [in /Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/Users/USER/PycharmProjects/flaskstructure/myData/routes.py", line 12, in before_request
    if current_user.is_authenticated:
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/Users/USER/PycharmProjects/flaskstructure/myData/models.py", line 64, in load_user
    return User.query.get(int(id))
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 924, in get
    ident, loading.load_on_pk_identity)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1007, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 250, in load_on_pk_identity
    return q.one()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2954, in one
    ret = self.one_or_none()
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
    ret = list(self)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/USER/PycharmProjects/flaskstructure/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user [SQL: 'SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen \nFROM user \nWHERE user.id = ?'] [parameters: (1,)] (Background on this error at: http://sqlalche.me/e/e3q8)
2018-10-05 20:41:04,252 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 20:41:04,855 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 20:52:53,530 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 20:52:54,012 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 20:56:23,155 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 21:00:29,290 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 21:00:29,765 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 21:04:30,153 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 21:04:52,857 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 21:04:58,159 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-05 21:04:58,749 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:17:14,399 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:17:15,161 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:27:14,518 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:27:15,354 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:28:18,393 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:28:18,917 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:29:26,766 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:29:27,783 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:30:47,513 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:30:48,357 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:32:26,474 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:32:27,000 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:41:16,364 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 15:41:16,949 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:24:28,142 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:24:28,617 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:26:32,308 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:28:20,697 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:28:59,594 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:29:00,052 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:29:39,629 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:29:40,125 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:30:49,541 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
2018-10-06 16:30:50,022 INFO: Myblog startup [in /Users/USER/PycharmProjects/flaskstructure/myData/__init__.py:45]
